upstream backend {
    server portfolio-web:18765;
}

server {
    listen 80;

    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /static {
        alias /app/staticfiles;
        access_log off;
        expires 30d;
        add_header Cache-Control "public";
    }
}