# Generated by Django 6.0.4 on 2026-04-25 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('introduction', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '경력',
                'verbose_name_plural': '경력',
            },
        ),
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': '내소개 표현',
                'verbose_name_plural': '내소개 표현',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('icon_class', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': '링크',
                'verbose_name_plural': '링크',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduction', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('introduction', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('is_represented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '이력서',
                'verbose_name_plural': '이력서',
                'ordering': ['-is_represented', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': '보유기술',
                'verbose_name_plural': '보유기술',
            },
        ),
        migrations.CreateModel(
            name='ResumeCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.career')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='careers',
            field=models.ManyToManyField(through='me.ResumeCareer', to='me.career'),
        ),
        migrations.CreateModel(
            name='ResumeExpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100)),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.expression')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='expressions',
            field=models.ManyToManyField(through='me.ResumeExpression', to='me.expression'),
        ),
        migrations.CreateModel(
            name='ResumeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.link')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='links',
            field=models.ManyToManyField(through='me.ResumeLink', to='me.link'),
        ),
        migrations.CreateModel(
            name='ResumeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.project')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.ManyToManyField(through='me.ResumeProject', to='me.project'),
        ),
        migrations.CreateModel(
            name='ResumeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.resume')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.skill')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(through='me.ResumeSkill', to='me.skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(to='me.skill'),
        ),
        migrations.AddField(
            model_name='career',
            name='skills',
            field=models.ManyToManyField(to='me.skill'),
        ),
    ]
