# Generated by Django 5.2.13 on 2026-04-25 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='description',
        ),
        migrations.CreateModel(
            name='CareerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('period', models.DateField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('order', models.IntegerField(default=100)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.career')),
            ],
            options={
                'verbose_name': '경력 프로젝트',
                'verbose_name_plural': '경력 프로젝트',
            },
        ),
    ]
