# Generated by Django 5.2.13 on 2026-04-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_remove_career_description_careerproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerproject',
            name='period',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
