# Generated by Django 5.2.13 on 2026-04-26 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_rename_description_project_content_project_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
    ]
