# Generated by Django 5.2.13 on 2026-04-26 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0005_rename_name_project_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(help_text='학교/전공, 자격증명 등 두꺼운 폰트', max_length=100)),
                ('content', models.CharField(help_text='졸업 상태, 발급 기관 등 회색 폰트', max_length=100)),
                ('order', models.IntegerField(default=100)),
            ],
            options={
                'verbose_name': '기타 사항',
                'verbose_name_plural': '기타 사항',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='others',
            field=models.ManyToManyField(to='me.others'),
        ),
        migrations.CreateModel(
            name='ResumeOhters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.others')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.resume')),
            ],
        ),
    ]
