# Generated by Django 5.2.13 on 2026-04-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_others_project_others_resumeohters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='others',
        ),
        migrations.AddField(
            model_name='resume',
            name='others',
            field=models.ManyToManyField(through='me.ResumeOhters', to='me.others'),
        ),
    ]
