# Generated by Django 5.2.13 on 2026-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0008_skill_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerproject',
            name='files',
            field=models.FileField(blank=True, upload_to='career_projects/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.FileField(blank=True, upload_to='projects/%Y/%m/%d'),
        ),
    ]
