# Generated by Django 5.2.13 on 2026-04-27 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0009_careerproject_files_project_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerproject',
            options={'verbose_name': '경력 프로젝트 이미지', 'verbose_name_plural': '경력 프로젝트 이미지'},
        ),
        migrations.RemoveField(
            model_name='careerproject',
            name='files',
        ),
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
        migrations.CreateModel(
            name='CareerProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='career_projects/%Y/%m/%d')),
                ('career_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.careerproject')),
            ],
            options={
                'verbose_name': '경력 프로젝트',
                'verbose_name_plural': '경력 프로젝트',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, upload_to='projects/%Y/%m/%d')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.project')),
            ],
            options={
                'verbose_name': '프로젝트 이미지',
                'verbose_name_plural': '프로젝트 이미지',
            },
        ),
    ]
