# Generated by Django 5.2.13 on 2026-04-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0010_alter_careerproject_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumeOhters',
            new_name='ResumeOthers',
        ),
        migrations.RenameField(
            model_name='resumeothers',
            old_name='other',
            new_name='others',
        ),
    ]
