# Generated by Django 5.2.13 on 2026-04-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0011_rename_resumeohters_resumeothers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerprojectimage',
            old_name='files',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='projectimage',
            old_name='files',
            new_name='file',
        ),
    ]
