# Generated by Django 5.2.13 on 2026-04-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0012_rename_files_careerprojectimage_file_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CareerProjectImage',
            new_name='CareerProjectFile',
        ),
        migrations.RenameModel(
            old_name='ProjectImage',
            new_name='ProjectFile',
        ),
    ]
