# Generated by Django 5.2.13 on 2026-04-28 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0013_rename_careerprojectimage_careerprojectfile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerproject',
            options={'verbose_name': '경력 프로젝트', 'verbose_name_plural': '경력 프로젝트'},
        ),
        migrations.AlterModelOptions(
            name='careerprojectfile',
            options={'verbose_name': '경력 프로젝트 참고자료', 'verbose_name_plural': '경력 프로젝트 참고자료'},
        ),
    ]
