# Generated by Django 5.2.13 on 2026-04-29 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0015_careerproject_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.project')),
            ],
            options={
                'verbose_name': '프로젝트 URL',
                'verbose_name_plural': '프로젝트 URL',
            },
        ),
    ]
