# Generated by Django 5.2.13 on 2026-04-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0016_projecturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecturl',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
