# Generated by Django 5.2.13 on 2026-04-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0017_projecturl_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
