# Generated by Django 5.2.13 on 2026-04-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0018_alter_career_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='introduction',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
