# Generated by Django 5.2.13 on 2026-05-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0019_career_note_alter_career_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='pdf_type',
            field=models.CharField(choices=[('RESUME', '이력서'), ('PORTFOLIO', '포트폴리오'), ('RESUME_PORTFOLIO', '이력서 + 포트폴리오')], default='RESUME_PORTFOLIO', max_length=20),
        ),
        migrations.AddField(
            model_name='link',
            name='pdf_type',
            field=models.CharField(choices=[('RESUME', '이력서'), ('PORTFOLIO', '포트폴리오'), ('RESUME_PORTFOLIO', '이력서 + 포트폴리오')], default='RESUME_PORTFOLIO', max_length=20),
        ),
        migrations.AddField(
            model_name='others',
            name='pdf_type',
            field=models.CharField(choices=[('RESUME', '이력서'), ('PORTFOLIO', '포트폴리오'), ('RESUME_PORTFOLIO', '이력서 + 포트폴리오')], default='RESUME_PORTFOLIO', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_type',
            field=models.CharField(choices=[('RESUME', '이력서'), ('PORTFOLIO', '포트폴리오'), ('RESUME_PORTFOLIO', '이력서 + 포트폴리오')], default='RESUME_PORTFOLIO', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='pdf_type',
            field=models.CharField(choices=[('RESUME', '이력서'), ('PORTFOLIO', '포트폴리오'), ('RESUME_PORTFOLIO', '이력서 + 포트폴리오')], default='RESUME_PORTFOLIO', max_length=20),
        ),
    ]
