# Generated by Django 5.2.13 on 2026-05-01 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0020_career_pdf_type_link_pdf_type_others_pdf_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '자기소개서',
                'verbose_name_plural': '자기소개서',
            },
        ),
        migrations.RemoveField(
            model_name='career',
            name='pdf_type',
        ),
        migrations.RemoveField(
            model_name='link',
            name='pdf_type',
        ),
        migrations.RemoveField(
            model_name='others',
            name='pdf_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pdf_type',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='pdf_type',
        ),
        migrations.CreateModel(
            name='ResumeCoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100)),
                ('cover_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.coverletter')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='me.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='cover_letters',
            field=models.ManyToManyField(through='me.ResumeCoverLetter', to='me.coverletter'),
        ),
    ]
