# Generated by Django 5.2.14 on 2026-06-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0022_resume_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='is_blinded_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_blinded_phone',
            field=models.BooleanField(default=False),
        ),
    ]
