# Generated by Django 5.2.14 on 2026-06-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0023_resume_is_blinded_email_resume_is_blinded_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='careerproject',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_blinded_email',
            field=models.BooleanField(choices=[(True, '예'), (False, '아니오')], default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_blinded_phone',
            field=models.BooleanField(choices=[(True, '예'), (False, '아니오')], default=False),
        ),
    ]
